source "%val{config}/plugins/plug.kak/rc/plug.kak"

colorscheme solarized-light

hook global WinCreate ^[^*]+$ %{editorconfig-load}

add-highlighter global/ show-whitespaces
add-highlighter global/ number-lines -relative -hlcursor

plug "andreyorst/powerline.kak" defer "powerline" %{
    powerline-toggle line_column off
    powerline-theme solarized-light
}
plug "andreyorst/fzf.kak" defer "powerline" %{
    map global normal <c-p> ': fzf-mode<ret>'
}
